### ISSUE TITLE
Models to upload here.

### ISSUE THREAD

**Issue by 38github** [pelennor2170/NAM_models#1]
http://coginthemachine.ddns.net/mnt/nam/

**Comment by spitfinelux** [comment]
Here 2 captures of my handmade point-to-point  Dumble Clone Amplifier OverDrive Special. 6L6 tubes used for Clean and Crunch/Overdrive gain. Will attempt to do other captures as I absolutely love this amp !

300 Epoch 0.21 for Crunch/Overdrive and 1000 Epoch 0.35 for Clean.
Don't forget to change the Input in NAM plugin. Lower the Input and set higher Gain, add some Reverb and you are good to go !
Enjoy the magic of Dumble tones :-)

[Spitfine-Carlos-Dumble-Clean_and_Overdrive_Channel.zip](https://github.com/pelennor2170/NAM_models/files/11132989/Spitfine-Carlos-Dumble-Clean_and_Overdrive_Channel.zip)
